# Generated by Django 4.1.2 on 2022-10-28 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_subscription_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=300),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('active', 'active')], max_length=100),
        ),
    ]
