# Generated by Django 4.1.2 on 2022-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_subscription_api', '0002_alter_customer_email_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=300, unique=True),
        ),
    ]
