# Generated by Django 4.1.2 on 2022-11-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_subscription_api', '0004_alter_customer_email_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('active', 'active')], max_length=100),
        ),
    ]
